service: starter-api
runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables: 
  NODE_ENV: production
  mongoUrl: {{MONGO_URL}}
  corsDomain: {{CORS_DOMAIN}}
  cookieSigningKey: {{COOKIE_SIGNING_KEY}}
  recaptchaSecretKey: {{RECAPTCHA_SECRET_KEY}}
